import type { Metadata } from "next";
import "./globals.css";
import { AuthGate } from "./auth-gate";
import { SessionAuthorizationProvider } from "../features/session/session-authorization";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="bg-slate-900 text-white">
        <SessionAuthorizationProvider>
          <AuthGate>{children}</AuthGate>
        </SessionAuthorizationProvider>
      </body>
    </html>
  );
}
